export const keyboardAngle = 70
export const maxLidAngle = 190
export const perspective = 2000
export const borderRadius1 = 3
export const borderRadius2 = 8
export const borderRadius3 = 20
export const boxShadow = '0px 0px 10px black'
export const prompt = '@felixwu.me:~$ '
export const historyLimit = 100
export const screenPadding = 10
export const mobileWidth = 600
export const userColor = 'yellow'
export const adminColor = '#ff7171'
export const backLabel = '< back'

export const color1 = '#222'
export const color2 = '#444'
export const color3 = '#555'
export const color4 = '#666'
export const color5 = '#777'
export const color6 = '#eee'
